### PR TITLE
Null safety & other fixes

### PR DESCRIPTION
**Pull request by reeteshranjan**
- Null safety support (added to 0.3.0)
- Fix for AndroidX related build warning
- Fix for embedding version related build warning
- Documentation regenerated for new null-safety version
- Fixed pub.dev scoring reported issues:
    - dartfmt formatting was missing on 2 files: ran on all files once again
    - old dependencies versions reported: fixed by upgrading
    - no null safety support: fixed as null safety is added now

### CODE REVIEW

**Comment by drenther** [comment]
@reeteshranjan should we bump to 1.0.0 on this? What do you think?

Even with the last PR it was major overhaul.

**Comment by reeteshranjan** [comment]
> @reeteshranjan should we bump to 1.0.0 on this? What do you think?
> 
> Even with the last PR it was major overhaul.

I think that makes sense even stability wise. I have been using the plugin pretty extensively and it's intent tunnel appears to be stable. The iOS mechanism is anyway even simpler, and with enough user protection in the presentation layer, it should be good to go.

**Comment by drenther** [comment]
Cool, please change it to 1.0.0 in changelog and spec yaml then and let's hit the first major version!!!

**Comment by reeteshranjan** [comment]
> Cool, please change it to 1.0.0 in changelog and spec yaml then and let's hit the first major version!!!

Done

**Review by drenther — APPROVED** [review]

**Comment by reeteshranjan** [comment]
@drenther should I merge and publish?

**Pull request merged**
