### PR TITLE
migrate to null safety

### PR DESCRIPTION
**Pull request by GJJ2019**
**fixes**  #23

### CODE REVIEW

**Comment by GJJ2019** [comment]
**warning version should get change to nearest big one** in this case 1.0.0

**Review by drenther — APPROVED** [review]

**Comment by reeteshranjan** [comment]
There would be few conflicts with the new broken-up file structure in #17. I think the best way would be to pull the main repo once #17 is merged and then bring null safety to the new structure.

**Comment by drenther** [comment]
I agree!

**Comment by drenther** [comment]
@GJJ2019 Apologies for the late reply here. Will you be able to pick up the Null Safety changes post merge of #17. If yes, that will be great. Thank you again!

**Comment by reeteshranjan** [comment]
@GJJ2019 @drenther it's much easier for me to fill in for the work done here on the base after merging #17 , hence done that in #27 . Thought would help avoid rework for @GJJ2019  this way.

**Comment by GJJ2019** [comment]
That's cool @reeteshranjan.
Let me know if u need some help in #27 @drenther

**Comment by drenther** [comment]
Closing this in favour of #27. Thanks again @reeteshranjan and @GJJ2019 for all the effort!

**Pull request closed without merging**
